### ISSUE TITLE
Register the package?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/LocalCoverage.jl#14]
cc: @tpapp @ExpandingMan

**Comment by tpapp** [comment]
Again, I don't have the bandwidth for this at the moment, but if anyone wants to do this that's fine with me.

**Comment by DilumAluthge** [comment]
@ExpandingMan How do you feel about registering?

**Comment by ExpandingMan** [comment]
I'm a bit confused about what exactly is going on here.  The package already appears in the registry.  I'm trying to register it again so that it recognizes the change in URL, but it claims the UUID has changed.  Looking at the UUID in general and comparing it to the `Project.toml`, that indeed seems to be the case.

I'm going to try just changing the UUID to the one that appears in the registry and trying again, but I'm pretty confused as to what happened here...

**Comment by ExpandingMan** [comment]
Ok, still not sure what's going on with the ID's, but it doesn't appear that one can change the URL via the tagbot or registration processes.  I have made a [PR](https://github.com/JuliaRegistries/General/pull/22544) to the General registry for the URL change.

**Comment by DilumAluthge** [comment]
@ExpandingMan Looks like it's working now?

Can you add the requested compat entries? https://github.com/JuliaRegistries/General/pull/22545

**Comment by ExpandingMan** [comment]
Sorry guys, I had forgotten about this, moved on to other things, but then had to come back to this.  I just made a PR that added another feature that I wound up needing and I figured others could benefit from.  I'll get that merged and then try tagging again.  I have added the `compat` entries.  Thanks all.

**Comment by tpapp** [comment]
Package is already registered.
