### ISSUE TITLE
RFC: API refactor

### ISSUE THREAD

**Issue by tpapp** [JuliaCI/LocalCoverage.jl#18]
I think we should accommodate the different ways people are using this package by a bit of API refactoring.

This is what I would propose:

1. `generate_coverage` just calls `Pkg.test(pkg; coverage = true)` and `Coverage.process_folder`, returning a custom struct `PackageCoverage` internal to this package that has the source locations and the processed coverage info. `generate_coverage` should, by default, clean up after itself (ie remove `*.cov` files that did not exist before).

2. a default `show` method for `PackageCoverage` just prints a pretty table, as implemented by @ffevotte in #17.

3. a new function `html_coverage(::PackageCoverage; open = false, dir = tempdir())` generates html, ideally in a temp directory, and open is if asked to. This replaces `open_coverage`. Incidentally, this should use DefaultApplication.jl.

4. `clean_coverage` and `coverage_summary` are removed as redundant.

**Comment by ffevotte** [comment]
I entirely agree with such a plan.

Points (1) and (2) alone would cover 90% of my needs. Making `genhtml` an additional, optional step would also improve usability on systems where `lcov` is not available (most notably Windows, where it is arguably hard to install)

For convenience, I would perhaps add
- a no-argument `generate_coverage` method, which operates on the currently active package.
- an `html_coverage(package_name::AbstractString; kwargs...)` method that first calls `generate_coverage` in order to get the `PackageCoverage` object on which to operate.

And of course I'm willing to help making this happen

**Comment by tpapp** [comment]
Closed by #30.

**Comment by goerz** [comment]
> `clean_coverage` and `coverage_summary` are removed as redundant.

What do I replace `coverage_summary` with?

References:
* https://github.com/JuliaQuantumControl/QuantumControlBase.jl/pull/32
* https://github.com/JuliaQuantumControl/QuantumControlBase.jl/blob/9c65e973cd740c36319a64a766fffbf4fa339f22/src/testutils.jl#L119

**Comment by tpapp** [comment]
`show` the value returned by `generate_coverage`.

(If that does not work, please open an issue.)

**Comment by goerz** [comment]
Thanks! I did get it to work, although I have some feedback on the new table format: https://github.com/JuliaCI/LocalCoverage.jl/issues/36
